### ISSUE TITLE
^.^

### ISSUE THREAD

**Issue by LuckyFishGeek** [MikuruM/Mikuru_Tamagotchi_ESP32#1]
如题

**Comment by MikuruM** [comment]
我确实准备这么写，可是有两个问题。一个是wifi库太大了装不下，另一个是不知道怎么在wifi彻底关闭（WiFi.mode( WIFI_OFF );这个函数）之后重启，一直开着的话会发热和费电。你可以在代码里搜一下wifi scan这个关键词，帮我改改2333

**Comment by LuckyFishGeek** [comment]
> 我确实准备这么写，可是有两个问题。一个是wifi库太大了装不下，另一个是不知道怎么在wifi彻底关闭（WiFi.mode( WIFI_OFF );这个函数）之后重启，一直开着的话会发热和费电。你可以在代码里搜一下wifi scan这个关键词，帮我改改2333

来个QQ  私聊 大兄弟

**Comment by MikuruM** [comment]
1486286346
